octopus:
  environments:
    - development
    - production
    - test
  development:
    grossman:
      adapter: mysql2
      database: grossman_dev
      host: localhost
      username: root
      password:
      pool: 5
      timeout: 5000

    gman_services:
      adapter: mysql2
      database: gman_services_dev
      host: localhost
      username: root
      password:
      pool: 5
      timeout: 5000

  production:
    grossman:
      adapter: mysql2
      database: grossman
      host: localhost
      username: root
      password:
      pool: 5
      timeout: 5000

    gman_services:
      adapter: mysql2
      database: gman_services
      host: localhost
      username: root
      password:
      pool: 5
      timeout: 5000

  test:
    grossman:
      adapter: mysql2
      database: grossman_test
      host: localhost
      username: root
      password:
      pool: 5
      timeout: 5000

    gman_services:
      adapter: mysql2
      database: gman_services_test
      host: localhost
      username: root
      password:
      pool: 5
      timeout: 5000
